version: '3.5'
services:
  api:
    image: bootcamp-api:latest
    container_name: bootcamp-api-container
    restart: on-failure
    ports:
      - "8077:8077"
  web: 
    image: bootcamp-frontend:latest
    container_name: bootcamp-frontend-container
    restart: on-failure
    depends_on:
      - api
    ports:
      - "80:80"

  